# Generated by Django 2.2.1 on 2019-06-14 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LodgingTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lodging_type', models.CharField(max_length=50, unique=True, verbose_name='Type of lodging')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Additional notes')),
            ],
            options={
                'verbose_name': 'Lodging',
                'verbose_name_plural': 'Lodging',
            },
        ),
    ]
