# Generated by Django 2.2.3 on 2019-07-10 04:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intakebus',
            name='arrival_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 10, 4, 32, 47, 847183, tzinfo=utc), verbose_name='Arrival time of bus'),
        ),
    ]
