# Generated by Django 3.2.4 on 2021-06-26 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capacity',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='donate',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='headofhousehold',
            name='detention_type',
            field=models.CharField(choices=[('mpp', 'Migrant Protection Protocols (MPP)'), ('t42', 'Title 42'), ('t42e', 'Title 42 Exemption'), ('cbp', 'Customs and Border Protection (CBP)'), ('icee', 'Immigration and Customes Enforcement (ICE) & Endeavors'), ('other', 'Other')], default='other', max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalheadofhousehold',
            name='detention_type',
            field=models.CharField(choices=[('mpp', 'Migrant Protection Protocols (MPP)'), ('t42', 'Title 42'), ('t42e', 'Title 42 Exemption'), ('cbp', 'Customs and Border Protection (CBP)'), ('icee', 'Immigration and Customes Enforcement (ICE) & Endeavors'), ('other', 'Other')], default='other', max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalorganization',
            name='historical_age_count',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='historicalorganization',
            name='historical_country_of_origin',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='historicalorganization',
            name='historical_destinations',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='historicalorganization',
            name='historical_detention_type',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='historicalorganization',
            name='historical_languages_spoken',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='historicalorganization',
            name='historical_needs',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='historicalorganization',
            name='historical_sex_count',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='historicalprofile',
            name='id',
            field=models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='historicalrequestqueue',
            name='id',
            field=models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='householdneed',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='language',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='message',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='historical_age_count',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='organization',
            name='historical_country_of_origin',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='organization',
            name='historical_destinations',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='organization',
            name='historical_detention_type',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='organization',
            name='historical_languages_spoken',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='organization',
            name='historical_needs',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='organization',
            name='historical_sex_count',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='requestqueue',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sitecoordinator',
            name='organization',
            field=models.ManyToManyField(to='intake.Organization'),
        ),
    ]
