# Generated by Django 3.1.6 on 2021-02-18 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='campaigns',
        ),
        migrations.AddField(
            model_name='profile',
            name='affiliation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='intake.organization', verbose_name='Affiliated Organization'),
        ),
        migrations.AddField(
            model_name='profile',
            name='focus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_focus', to='intake.capacity', verbose_name='Current Focus'),
        ),
    ]
