# Generated by Django 2.2.1 on 2019-05-24 21:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('intake', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asylees',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=300, verbose_name="Asylee's first name")),
                ('last_name', models.CharField(max_length=300, verbose_name="Asylee's last name")),
                ('sex', models.CharField(choices=[('female', 'Female'), ('male', 'Male')], default='Female', max_length=2, verbose_name="Asylee's sex")),
                ('date_of_birth', models.DateField(verbose_name="Asylee's date of birth (mdy?)")),
                ('country_of_origin', models.CharField(choices=[('Most Common', (('brazil', 'Brazil'), ('el salvador', 'El Salvador'), ('guatemala', 'Guatemala'), ('honduras', 'Honduras'))), ('Less Common', (('belize', 'Belize'), ('bolivia', 'Bolivia'), ('colombia', 'Colombia'), ('ecuador', 'Ecuador'), ('haiti', 'Haiti'), ('jamaica', 'Jamaica'), ('mexico', 'Mexico'), ('nicaragua', 'Nicaragua'), ('panama', 'Panama'), ('peru', 'Peru'), ('venezuela', 'Venezuela'))), ('other', 'Other')], default='guatemala', max_length=2, verbose_name="Asylee's country of origin")),
                ('phone_number', models.CharField(max_length=300, verbose_name="sponsor's phone number")),
                ('tsa_done', models.BooleanField(default=False, verbose_name='Is TSA done?')),
                ('legal_done', models.BooleanField(default=False, verbose_name='Is legal done?')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('notes', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='intake.Notes')),
            ],
        ),
        migrations.RenameField(
            model_name='travelplans',
            old_name='travel_type',
            new_name='travel_mode',
        ),
        migrations.RemoveField(
            model_name='volunteers',
            name='email_address',
        ),
        migrations.AddField(
            model_name='family',
            name='intake_bus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='intake.IntakeBuses'),
        ),
        migrations.AddField(
            model_name='intakebuses',
            name='number',
            field=models.CharField(help_text='Identifying number for bus', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='volunteers',
            name='email',
            field=models.EmailField(help_text='Required. Inform a valid email address.', max_length=300, null=True, verbose_name="volunteer's email"),
        ),
        migrations.AddField(
            model_name='volunteers',
            name='notes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='intake.Notes'),
        ),
        migrations.AddField(
            model_name='volunteers',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='medical',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='intake.Asylees', verbose_name='asylee patient'),
        ),
        migrations.AlterField(
            model_name='volunteers',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='Asylee',
        ),
        migrations.AddField(
            model_name='asylees',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='intake.Family'),
        ),
        migrations.AddField(
            model_name='asylees',
            name='intake_volunteer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='intake.Volunteers'),
        ),
        migrations.AddField(
            model_name='asylees',
            name='notes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='intake.Notes'),
        ),
    ]
