# Generated by Django 2.2.2 on 2019-06-17 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_student',
            new_name='is_point_of_contact',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_teacher',
            new_name='is_team_lead',
        ),
    ]
