# Generated by Django 2.2.3 on 2019-07-15 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0003_auto_20190528_1558'),
        ('intake', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='campaign',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shortener.UrlMap', verbose_name='Active intake campaigns'),
        ),
    ]
