# Generated by Django 3.1.6 on 2021-02-24 22:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asylee',
            name='covid_vaccine_shots',
        ),
        migrations.AddField(
            model_name='asylee',
            name='covid_vaccine_doses',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)], verbose_name='COVID vaccine doses received'),
        ),
        migrations.AlterField(
            model_name='asylee',
            name='vaccine_received',
            field=models.CharField(choices=[('pfizer', 'Pfizer (0/1/2)'), ('moderna', 'Moderna (0/1/2)'), ('j_and_j', 'Johnson & Johnson (0/1)'), ('astra_zeneca', 'AstraZeneca (0/1)'), ('unknown', 'Unknown (0/1/2)'), ('other', 'Other')], max_length=100, null=True, verbose_name='Vaccine manufacturer'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='specialty',
            field=models.CharField(choices=[('clothes', 'Clothes'), ('departurebags', 'Departure Bags'), ('food', 'Food'), ('hotelrunner', 'Hotel Runner'), ('intake', 'Intake'), ('medical', 'Medical'), ('travel', 'Travel'), ('transportation', 'Transportation'), ('volunteercoordinator', 'Volunteer Coordinator'), ('other', 'Other')], default='other', max_length=100, verbose_name='Team lead area'),
        ),
    ]
