# Generated by Django 2.2.3 on 2019-07-10 22:33

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0003_auto_20190528_1558'),
        ('intake', '0002_auto_20190709_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='campaign',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shortener.UrlMap', verbose_name='Active intake campaigns'),
        ),
        migrations.AlterField(
            model_name='intakebus',
            name='arrival_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 10, 22, 33, 27, 219338, tzinfo=utc), verbose_name='Arrival time of bus'),
        ),
        migrations.AlterField(
            model_name='user',
            name='languages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Latin', (('english', 'English'), ('spanish', 'Spanish'), ('portuguese', 'Portuguese'), ('french', 'French'))), ('Maya', (('achi', 'Achi'), ('awakatek', 'Awakatek'), ('chorti', "Ch'orti'"), ('chuj', 'Chuj'), ('itza', "Itza'"), ('ixil', 'Ixil'), ('jakaltek', 'Jakaltek'), ('kiche', "K'iche'"), ('kaqchiquel', 'Kaqchiquel'), ('mam', 'Mam'), ('mopan', 'Mopan'), ('poqomam', 'Poqomam'), ('poqomchi', "Poqomchi'"), ('qanjobal', "Q'anjob'al"), ('qeqchi', "Q'eqchi'"), ('sakapultek', 'Sakapultek'), ('sipakapense', 'Sipakapense'), ('tektitek', 'Tektitek'), ('tzutujil', "Tz'utujil"), ('upsantek', 'Upsantek'))), ('other', 'Other')], default='english', max_length=100, verbose_name='Languages spoken'), size=None),
        ),
    ]
