# Generated by Django 2.2.2 on 2019-06-17 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0002_auto_20190616_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='Admin Baker', max_length=300, verbose_name="Volunteer's name"),
            preserve_default=False,
        ),
    ]
