# Generated by Django 3.1.6 on 2021-02-19 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0002_auto_20210218_1559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_site_coordinator',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_team_lead',
        ),
        migrations.AddField(
            model_name='profile',
            name='organizations_created',
            field=models.ManyToManyField(related_name='organizations_created', to='intake.Organization', verbose_name='Organizations created'),
        ),
    ]
