# Generated by Django 3.1.6 on 2021-02-17 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0002_campaign_campaign'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intakebus',
            name='families',
        ),
        migrations.AddField(
            model_name='intakebus',
            name='headsofhousehold',
            field=models.ManyToManyField(to='intake.HeadOfHousehold', verbose_name='Heads of Households'),
        ),
    ]
