# Generated by Django 2.2.3 on 2019-07-09 04:20

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0002_auto_20190707_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intakebus',
            name='arrival_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 9, 4, 20, 29, 594207, tzinfo=utc), verbose_name='Arrival time of bus'),
        ),
        migrations.AlterField(
            model_name='travelplan',
            name='arranged_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
