# Generated by Django 3.1.6 on 2021-02-24 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0002_auto_20210224_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asylee',
            name='vaccine_received',
            field=models.CharField(choices=[('pfizer', 'Pfizer'), ('moderna', 'Moderna'), ('j_and_j', 'Johnson & Johnson'), ('astra_zeneca', 'AstraZeneca'), ('unknown', 'Unknown'), ('other', 'Other')], max_length=100, null=True, verbose_name='Vaccine manufacturer'),
        ),
    ]
