# Generated by Django 2.2.3 on 2019-08-06 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0002_campaign_campaign'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitecoordinator',
            name='organization',
        ),
        migrations.AddField(
            model_name='sitecoordinator',
            name='organization',
            field=models.ManyToManyField(null=True, to='intake.Organization'),
        ),
    ]
