# Generated by Django 2.2.3 on 2019-07-03 23:06

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0002_auto_20190703_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asylee',
            name='sex',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intake.Sex'),
        ),
        migrations.AlterField(
            model_name='intakebus',
            name='arrival_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 3, 23, 6, 33, 915842, tzinfo=utc), verbose_name='Arrival time of bus'),
        ),
    ]
