# Generated by Django 2.2.3 on 2019-08-06 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0002_campaign_campaign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestqueue',
            name='site_coordinator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='intake.SiteCoordinator'),
        ),
        migrations.AlterField(
            model_name='sitecoordinator',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='intake.Organization'),
        ),
    ]
