# Generated by Django 2.2.1 on 2019-06-14 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0002_lodgingtypes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LodgingTypes',
            new_name='LodgingType',
        ),
    ]
