# Generated by Django 3.1.7 on 2021-02-27 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0002_auto_20210227_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asylee',
            name='phone_number',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name="Asylee's phone number"),
        ),
    ]
