# Generated by Django 3.1.6 on 2021-02-19 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0003_auto_20210218_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='can_create_organization',
            field=models.BooleanField(default=False, verbose_name='Able to create organizations'),
        ),
    ]
