# Generated by Django 3.1.7 on 2021-04-07 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0003_auto_20210406_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalorganization',
            name='historical_age_count',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='historicalorganization',
            name='historical_country_of_origin',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='historicalorganization',
            name='historical_destinations',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='historicalorganization',
            name='historical_detention_type',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='historicalorganization',
            name='historical_languages_spoken',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='historicalorganization',
            name='historical_needs',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='historicalorganization',
            name='historical_sex_count',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='organization',
            name='historical_age_count',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='organization',
            name='historical_country_of_origin',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='organization',
            name='historical_destinations',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='organization',
            name='historical_detention_type',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='organization',
            name='historical_languages_spoken',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='organization',
            name='historical_needs',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='organization',
            name='historical_sex_count',
            field=models.JSONField(default=dict),
        ),
    ]
