# Generated by Django 3.1.7 on 2021-02-28 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0003_auto_20210227_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asylee',
            name='vaccine_received',
            field=models.CharField(blank=True, choices=[('pfizer', 'Pfizer'), ('moderna', 'Moderna'), ('j_and_j', 'Johnson & Johnson'), ('astra_zeneca', 'AstraZeneca'), ('unknown', 'Unknown'), ('other', 'Other')], max_length=100, null=True, verbose_name='Vaccine manufacturer'),
        ),
    ]
