# Generated by Django 3.1.6 on 2021-02-17 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0003_auto_20210216_2109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='headofhousehold',
            name='family_name',
        ),
    ]
