# Generated by Django 2.2.3 on 2019-07-10 01:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0003_auto_20190708_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intakebus',
            name='arrival_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 10, 1, 50, 24, 81740, tzinfo=utc), verbose_name='Arrival time of bus'),
        ),
    ]
