# Generated by Django 3.2.4 on 2021-06-30 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0003_auto_20210626_2146'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalorganization',
            old_name='associated_airport',
            new_name='airport_of_record',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='associated_airport',
            new_name='airport_of_record',
        ),
    ]
