# Generated by Django 2.2.3 on 2019-07-05 19:17

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0003_auto_20190703_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asylee',
            name='family',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='intake.Family'),
        ),
        migrations.AlterField(
            model_name='intakebus',
            name='arrival_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 5, 19, 17, 0, 603658, tzinfo=utc), verbose_name='Arrival time of bus'),
        ),
    ]
