# Generated by Django 2.2.3 on 2019-07-16 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0003_auto_20190715_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='intake.Organization'),
        ),
    ]
