# Generated by Django 3.2.1 on 2021-05-06 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0004_auto_20210406_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalorganization',
            name='historical_age_count',
            field=models.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='historicalorganization',
            name='historical_country_of_origin',
            field=models.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='historicalorganization',
            name='historical_destinations',
            field=models.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='historicalorganization',
            name='historical_detention_type',
            field=models.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='historicalorganization',
            name='historical_languages_spoken',
            field=models.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='historicalorganization',
            name='historical_needs',
            field=models.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='historicalorganization',
            name='historical_sex_count',
            field=models.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='historicalorganization',
            name='historical_travel_duration',
            field=models.JSONField(default={'Air': [0, 0], 'Bus': [0, 0], 'Car': [0, 0], 'Train': [0, 0], 'other': [0, 0]}),
        ),
        migrations.AlterField(
            model_name='organization',
            name='historical_age_count',
            field=models.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='organization',
            name='historical_country_of_origin',
            field=models.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='organization',
            name='historical_destinations',
            field=models.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='organization',
            name='historical_detention_type',
            field=models.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='organization',
            name='historical_languages_spoken',
            field=models.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='organization',
            name='historical_needs',
            field=models.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='organization',
            name='historical_sex_count',
            field=models.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='organization',
            name='historical_travel_duration',
            field=models.JSONField(default={'Air': [0, 0], 'Bus': [0, 0], 'Car': [0, 0], 'Train': [0, 0], 'other': [0, 0]}),
        ),
    ]
