# Generated by Django 3.1.6 on 2021-02-17 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0004_remove_headofhousehold_family_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headofhousehold',
            name='lodging',
            field=models.CharField(max_length=300, null=True, verbose_name='Room assignment'),
        ),
    ]
