# Generated by Django 3.2.5 on 2021-07-12 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0004_auto_20210630_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='asylee',
            name='pant_size',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Pant size'),
        ),
        migrations.AddField(
            model_name='asylee',
            name='shirt_size',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Shirt size'),
        ),
        migrations.AddField(
            model_name='asylee',
            name='shoe_size',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Shoe size'),
        ),
        migrations.AddField(
            model_name='historicalasylee',
            name='pant_size',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Pant size'),
        ),
        migrations.AddField(
            model_name='historicalasylee',
            name='shirt_size',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Shirt size'),
        ),
        migrations.AddField(
            model_name='historicalasylee',
            name='shoe_size',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Shoe size'),
        ),
        migrations.AddField(
            model_name='historicalheadofhousehold',
            name='pant_size',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Pant size'),
        ),
        migrations.AddField(
            model_name='historicalheadofhousehold',
            name='shirt_size',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Shirt size'),
        ),
        migrations.AddField(
            model_name='historicalheadofhousehold',
            name='shoe_size',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Shoe size'),
        ),
    ]
