# Generated by Django 3.1.6 on 2021-02-16 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0004_auto_20210205_1323'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000)),
                ('dismissible', models.BooleanField(default=True)),
                ('message_type', models.CharField(choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('success', 'Success'), ('danger', 'Danger'), ('warning', 'Warning'), ('info', 'Info'), ('light', 'Light'), ('dark', 'Dark')], max_length=100, verbose_name='Message')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
            },
        ),
        migrations.AddField(
            model_name='asylee',
            name='had_covid_disease',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='asylee',
            name='had_covid_vaccine',
            field=models.BooleanField(default=False),
        ),
    ]
