# Generated by Django 2.2.3 on 2019-08-01 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0004_auto_20190715_2047'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capacity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Capacity')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=100, verbose_name='Language Spoken')),
            ],
        ),
        migrations.RemoveField(
            model_name='family',
            name='languages',
        ),
        migrations.RemoveField(
            model_name='user',
            name='capacities',
        ),
        migrations.RemoveField(
            model_name='user',
            name='languages',
        ),
        migrations.AddField(
            model_name='family',
            name='languages',
            field=models.ManyToManyField(to='intake.Language', verbose_name='Languages Spoken'),
        ),
        migrations.AddField(
            model_name='user',
            name='capacities',
            field=models.ManyToManyField(to='intake.Capacity', verbose_name='Capacities'),
        ),
        migrations.AddField(
            model_name='user',
            name='languages',
            field=models.ManyToManyField(to='intake.Language', verbose_name='Languages Spoken'),
        ),
    ]
