# Generated by Django 3.1.6 on 2021-02-19 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0004_profile_can_create_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestqueue',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='intake.organization'),
        ),
        migrations.AlterField(
            model_name='requestqueue',
            name='site_coordinator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='intake.profile'),
        ),
    ]
