# Generated by Django 2.2.3 on 2019-07-10 22:44

import django.contrib.postgres.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0004_auto_20190710_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intakebus',
            name='arrival_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Arrival time of bus'),
        ),
        migrations.AlterField(
            model_name='user',
            name='languages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Latin', (('english', 'English'), ('spanish', 'Spanish'), ('portuguese', 'Portuguese'), ('french', 'French'))), ('Maya', (('achi', 'Achi'), ('awakatek', 'Awakatek'), ('chorti', "Ch'orti'"), ('chuj', 'Chuj'), ('itza', "Itza'"), ('ixil', 'Ixil'), ('jakaltek', 'Jakaltek'), ('kiche', "K'iche'"), ('kaqchiquel', 'Kaqchiquel'), ('mam', 'Mam'), ('mopan', 'Mopan'), ('poqomam', 'Poqomam'), ('poqomchi', "Poqomchi'"), ('qanjobal', "Q'anjob'al"), ('qeqchi', "Q'eqchi'"), ('sakapultek', 'Sakapultek'), ('sipakapense', 'Sipakapense'), ('tektitek', 'Tektitek'), ('tzutujil', "Tz'utujil"), ('upsantek', 'Upsantek'))), ('other', 'Other')], default='english', max_length=100, verbose_name='Languages spoken'), null=True, size=None),
        ),
    ]
