# Generated by Django 3.1.7 on 2021-03-01 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0004_auto_20210227_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headofhousehold',
            name='destination_city',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Destination city'),
        ),
        migrations.AlterField(
            model_name='headofhousehold',
            name='lodging',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Room assignment'),
        ),
    ]
