# Generated by Django 2.2.1 on 2019-06-01 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0004_auto_20190601_0250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locations',
            name='name',
            field=models.CharField(help_text='Dolor', max_length=300, verbose_name='Sit amet'),
        ),
    ]
