# Generated by Django 2.2.1 on 2019-06-01 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0005_auto_20190601_0316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locations',
            name='name',
            field=models.CharField(max_length=300),
        ),
    ]
