# Generated by Django 3.2.5 on 2021-07-13 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0005_auto_20210712_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='asylee',
            name='underwear_size',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Underwear size'),
        ),
        migrations.AddField(
            model_name='historicalasylee',
            name='underwear_size',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Underwear size'),
        ),
        migrations.AddField(
            model_name='historicalheadofhousehold',
            name='underwear_size',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Underwear size'),
        ),
    ]
