# Generated by Django 2.2.3 on 2019-07-10 22:47

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0005_auto_20190710_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='capacities',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('activities', 'Activities'), ('changeofaddress', 'Change of Address'), ('clothes', 'Clothes'), ('departurebags', 'Departure Bags'), ('food', 'Food'), ('intake', 'Intake'), ('medical', 'Medical'), ('travel', 'Travel'), ('transport', 'Transport'), ('volunteercoordinator', 'Volunteer Coordinator'), ('other', 'Other')], default='other', max_length=100, verbose_name='Capacities'), null=True, size=None),
        ),
    ]
