# Generated by Django 2.2.3 on 2019-07-06 02:02

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0005_auto_20190705_1934'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Name of the staging location')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Additional notes')),
            ],
        ),
        migrations.AlterField(
            model_name='intakebus',
            name='arrival_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 6, 2, 2, 39, 203050, tzinfo=utc), verbose_name='Arrival time of bus'),
        ),
        migrations.CreateModel(
            name='NewOrganization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_valid', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=500, unique=True, verbose_name='Name of the organization')),
                ('city', models.CharField(max_length=500, null=True, verbose_name='City')),
                ('url', models.CharField(max_length=500, null=True, verbose_name='Website')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Additional notes')),
                ('locations', models.ManyToManyField(to='intake.NewLocation', verbose_name='Locations')),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='intake.State', verbose_name='State')),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
            },
        ),
    ]
