# Generated by Django 3.1.7 on 2021-03-02 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0006_auto_20210301_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asylee',
            name='a_number',
            field=models.CharField(default='A-', max_length=20, verbose_name='Alien number'),
        ),
    ]
