# Generated by Django 2.2.3 on 2019-07-06 03:34

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0003_auto_20190528_1558'),
        ('intake', '0006_auto_20190705_2002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='affiliations',
        ),
        migrations.AddField(
            model_name='campaign',
            name='campaign',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shortener.UrlMap', verbose_name='Active intake campaigns'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='organization',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='intake.Organization'),
        ),
        migrations.AlterField(
            model_name='intakebus',
            name='arrival_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 6, 3, 34, 1, 254185, tzinfo=utc), verbose_name='Arrival time of bus'),
        ),
    ]
