# Generated by Django 3.1.6 on 2021-02-20 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0006_remove_profile_focus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
    ]
