# Generated by Django 3.2.5 on 2021-07-13 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0006_auto_20210713_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asylee',
            name='vaccine_received',
            field=models.CharField(blank=True, choices=[('pfizer', 'Pfizer'), ('moderna', 'Moderna'), ('j_and_j', 'Johnson & Johnson'), ('astra_zeneca', 'AstraZeneca'), ('sinovac', 'Sinovac'), ('sinopharm', 'Sinopharm'), ('sputnikv', 'Sputnik V'), ('sputniklite', 'Sputnix Lite'), ('janssen', 'Janssen'), ('convidecia', 'Convidecia'), ('coronavac', 'CoronaVac'), ('unknown', 'Unknown'), ('other', 'Other')], max_length=100, null=True, verbose_name='Vaccine manufacturer'),
        ),
        migrations.AlterField(
            model_name='historicalasylee',
            name='vaccine_received',
            field=models.CharField(blank=True, choices=[('pfizer', 'Pfizer'), ('moderna', 'Moderna'), ('j_and_j', 'Johnson & Johnson'), ('astra_zeneca', 'AstraZeneca'), ('sinovac', 'Sinovac'), ('sinopharm', 'Sinopharm'), ('sputnikv', 'Sputnik V'), ('sputniklite', 'Sputnix Lite'), ('janssen', 'Janssen'), ('convidecia', 'Convidecia'), ('coronavac', 'CoronaVac'), ('unknown', 'Unknown'), ('other', 'Other')], max_length=100, null=True, verbose_name='Vaccine manufacturer'),
        ),
        migrations.AlterField(
            model_name='historicalheadofhousehold',
            name='vaccine_received',
            field=models.CharField(blank=True, choices=[('pfizer', 'Pfizer'), ('moderna', 'Moderna'), ('j_and_j', 'Johnson & Johnson'), ('astra_zeneca', 'AstraZeneca'), ('sinovac', 'Sinovac'), ('sinopharm', 'Sinopharm'), ('sputnikv', 'Sputnik V'), ('sputniklite', 'Sputnix Lite'), ('janssen', 'Janssen'), ('convidecia', 'Convidecia'), ('coronavac', 'CoronaVac'), ('unknown', 'Unknown'), ('other', 'Other')], max_length=100, null=True, verbose_name='Vaccine manufacturer'),
        ),
    ]
