# Generated by Django 3.1.6 on 2021-02-21 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0007_auto_20210219_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headofhousehold',
            name='country_of_origin',
            field=models.CharField(choices=[('The Americas', (('guatemala', 'Guatemala'), ('honduras', 'Honduras'), ('elsalvador', 'El Salvador'), ('mexico', 'Mexico'), ('argentina', 'Argentina'), ('bolivia', 'Bolivia'), ('brazil', 'Brazil'), ('chile', 'Chile'), ('colombia', 'Colombia'), ('costarica', 'Costa Rica'), ('cuba', 'Cuba'), ('dominicanrepublic', 'Dominican Republic'), ('ecuador', 'Ecuador'), ('frenchguiana', 'French Guiana'), ('guadeloupe', 'Guadeloupe'), ('haiti', 'Haiti'), ('martinique', 'Martinique'), ('mexico', 'Mexico'), ('nicaragua', 'Nicaragua'), ('panama', 'Panama'), ('paraguay', 'Paraguay'), ('peru', 'Peru'), ('saintmartin', 'Saint Martin'), ('uruguay', 'Uruguay'), ('venezuela', 'Venezuela'))), ('Africa', (('algeria', 'Algeria'), ('angola', 'Angola'), ('benin', 'Benin'), ('botswana', 'Botswana'), ('burkinafaso', 'Burkina Faso'), ('burundi', 'Burundi'), ('cameroon', 'Cameroon'), ('canaryislands', 'Canary Islands'), ('capeverde', 'Cape Verde'), ('centralafricanrepublic', 'Central African Republic'), ('ceuta', 'Ceuta'), ('chad', 'Chad'), ('comoros', 'Comoros'), ('cotedivoire', "Côte d'Ivoire"), ('democraticrepublicofthecongo', 'Democratic Republic of the Congo'), ('djibouti', 'Djibouti'), ('egypt', 'Egypt'), ('equatorialguinea', 'Equatorial Guinea'), ('eritrea', 'Eritrea'), ('ethiopia', 'Ethiopia'), ('gabon', 'Gabon'), ('gambia', 'Gambia'), ('ghana', 'Ghana'), ('guinea', 'Guinea'), ('guinea-bissau', 'Guinea-Bissau'), ('kenya', 'Kenya'), ('lesotho', 'Lesotho'), ('liberia', 'Liberia'), ('libya', 'Libya'), ('madagascar', 'Madagascar'), ('madeira', 'Madeira'), ('malawi', 'Malawi'), ('mali', 'Mali'), ('mauritania', 'Mauritania'), ('mauritius', 'Mauritius'), ('mayotte', 'Mayotte'), ('melilla', 'Melilla'), ('morocco', 'Morocco'), ('mozambique', 'Mozambique'), ('namibia', 'Namibia'), ('niger', 'Niger'), ('nigeria', 'Nigeria'), ('republicofthecongo', 'Republic of the Congo'), ('reunion', 'Réunion'), ('rwanda', 'Rwanda'), ('sainthelena', 'Saint Helena'), ('saotomeandpríncipe', 'São Tomé and Príncipe'), ('senegal', 'Senegal'), ('seychelles', 'Seychelles'), ('sierraleone', 'Sierra Leone'), ('somalia', 'Somalia'), ('southafrica', 'South Africa'), ('sudan', 'Sudan'), ('swaziland', 'Swaziland'), ('tanzania', 'Tanzania'), ('togo', 'Togo'), ('tunisia', 'Tunisia'), ('uganda', 'Uganda'), ('westernsahara', 'Western Sahara'), ('zambia', 'Zambia'), ('zimbabwe', 'Zimbabwe'))), ('other', 'Other')], default='guatemala', max_length=100, verbose_name='Country of origin'),
        ),
    ]
