# Generated by Django 2.2.1 on 2019-06-02 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0007_auto_20190601_0319'),
    ]

    operations = [
        migrations.AddField(
            model_name='intakebuses',
            name='destination',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='intake.Locations'),
        ),
        migrations.AlterField(
            model_name='locations',
            name='name',
            field=models.CharField(max_length=300),
        ),
    ]
