# Generated by Django 2.2.3 on 2019-07-06 04:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0007_auto_20190705_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intakebus',
            name='arrival_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 6, 4, 7, 2, 158201, tzinfo=utc), verbose_name='Arrival time of bus'),
        ),
    ]
