# Generated by Django 3.1.7 on 2021-03-03 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0007_auto_20210301_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='zip',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name="Sponsor's ZIP code"),
        ),
    ]
