# Generated by Django 2.2.3 on 2019-07-12 17:43

from django.db import migrations
import hashid_field.field


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0007_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='id',
        ),
        migrations.AlterField(
            model_name='book',
            name='reference_id',
            field=hashid_field.field.HashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length=7, primary_key=True, serialize=False),
        ),
    ]
