# Generated by Django 2.2.3 on 2019-07-06 21:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0008_auto_20190705_2207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='neworganization',
            name='locations',
        ),
        migrations.RemoveField(
            model_name='neworganization',
            name='state',
        ),
        migrations.RemoveField(
            model_name='location',
            name='organization',
        ),
        migrations.AlterField(
            model_name='intakebus',
            name='arrival_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 6, 21, 43, 44, 896621, tzinfo=utc), verbose_name='Arrival time of bus'),
        ),
        migrations.DeleteModel(
            name='NewLocation',
        ),
        migrations.DeleteModel(
            name='NewOrganization',
        ),
    ]
