# Generated by Django 2.2.3 on 2019-07-12 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0008_auto_20190712_1143'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='reference_id',
            new_name='id',
        ),
    ]
