# Generated by Django 3.1.7 on 2021-03-03 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0008_sponsor_zip'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sponsor',
            old_name='zip',
            new_name='zip_code',
        ),
    ]
