# Generated by Django 2.2.1 on 2019-06-03 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0008_auto_20190602_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intakebuses',
            name='arrival_time',
            field=models.DateTimeField(blank=True, help_text="Bus' time of arrival at staging location", null=True),
        ),
        migrations.AlterField(
            model_name='intakebuses',
            name='destination',
            field=models.ForeignKey(help_text='Where the bus dropped off asylees', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='intake.Locations'),
        ),
        migrations.AlterField(
            model_name='intakebuses',
            name='origin',
            field=models.CharField(help_text='Where the bus came from', max_length=100),
        ),
        migrations.AlterField(
            model_name='locations',
            name='name',
            field=models.CharField(help_text='Name of the refugee staging location', max_length=300),
        ),
        migrations.AlterField(
            model_name='locations',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes', null=True),
        ),
        migrations.AlterField(
            model_name='lodging',
            name='description',
            field=models.CharField(help_text='Description of lodging', max_length=200),
        ),
        migrations.AlterField(
            model_name='lodging',
            name='lodging_type',
            field=models.CharField(choices=[('hotel', 'Hotel/Motel Room'), ('dorm', 'Dormitory Room'), ('other', 'Other')], default='dorm', help_text='What type of lodging', max_length=2),
        ),
        migrations.AlterField(
            model_name='travelplans',
            name='arranged_by',
            field=models.ForeignKey(help_text='Volunteer who arranged travel plans', on_delete=django.db.models.deletion.DO_NOTHING, to='intake.Volunteers', verbose_name='Travel arranged by (volunteer)'),
        ),
        migrations.AlterField(
            model_name='travelplans',
            name='confirmation',
            field=models.CharField(help_text='Confirmation details', max_length=200),
        ),
        migrations.AlterField(
            model_name='volunteers',
            name='email',
            field=models.EmailField(help_text="Volunteer's email", max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='volunteers',
            name='name',
            field=models.CharField(help_text="Volunteer's name", max_length=300),
        ),
        migrations.AlterField(
            model_name='volunteers',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes', null=True),
        ),
        migrations.AlterField(
            model_name='volunteers',
            name='phone_number',
            field=models.CharField(help_text="Volunteer's phone number", max_length=300),
        ),
        migrations.AlterField(
            model_name='volunteers',
            name='volunteer_type',
            field=models.ManyToManyField(help_text="Volunteer's capacities", to='intake.VolunteerTypes'),
        ),
        migrations.CreateModel(
            name='Organizations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name of the organization', max_length=300)),
                ('location', models.CharField(help_text='City, State of the organization', max_length=300)),
                ('organization_head', models.OneToOneField(help_text='Name of the head of the organization', on_delete=django.db.models.deletion.CASCADE, to='intake.Volunteers')),
            ],
        ),
    ]
