# Generated by Django 3.1.6 on 2021-02-21 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0008_auto_20210221_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headofhousehold',
            name='asylees',
            field=models.ManyToManyField(default=None, related_name='head_of_household', to='intake.Asylee', verbose_name='Asylees'),
        ),
    ]
