# Generated by Django 3.1.6 on 2021-02-22 04:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0009_auto_20210221_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='asylee',
            name='a_number',
            field=models.CharField(default='A-00000000', max_length=20, verbose_name='Alien number'),
        ),
        migrations.AddField(
            model_name='asylee',
            name='covid_vaccine_shots',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)]),
        ),
        migrations.AddField(
            model_name='asylee',
            name='sick_covid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='asylee',
            name='sick_other',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='asylee',
            name='vaccine_received',
            field=models.CharField(choices=[('pfizer', 'Pfizer'), ('moderna', 'Moderna'), ('j_and_j', 'Johnson & Johnson'), ('astra_zeneca', 'AstraZeneca'), ('other', 'Other')], max_length=100, null=True),
        ),
    ]
