# Generated by Django 2.2.1 on 2019-06-04 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0009_auto_20190603_2216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizations',
            name='organization_head',
        ),
        migrations.AddField(
            model_name='organizations',
            name='head_email',
            field=models.EmailField(default='hello@.com', help_text="Head of organization's email", max_length=300),
        ),
        migrations.AddField(
            model_name='organizations',
            name='head_name',
            field=models.CharField(default='J Doe', help_text="Head of organization's name", max_length=300),
        ),
        migrations.AddField(
            model_name='organizations',
            name='head_phone_number',
            field=models.CharField(default='505-867-5309', help_text="Head of organization's phone number", max_length=300),
        ),
        migrations.AddField(
            model_name='volunteers',
            name='organizations',
            field=models.ManyToManyField(help_text='Organizations to which the volunteer belongs', to='intake.Organizations'),
        ),
    ]
