# Generated by Django 2.2.3 on 2019-07-06 22:09

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0009_auto_20190706_1543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asylee',
            name='family',
        ),
        migrations.RemoveField(
            model_name='family',
            name='intake_bus',
        ),
        migrations.RemoveField(
            model_name='intakebus',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='medical',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='sponsor',
            name='family',
        ),
        migrations.AddField(
            model_name='asylee',
            name='medical',
            field=models.ManyToManyField(to='intake.Medical', verbose_name='Medical Issues'),
        ),
        migrations.AddField(
            model_name='family',
            name='asylees',
            field=models.ManyToManyField(to='intake.Asylee', verbose_name='Asylees'),
        ),
        migrations.AddField(
            model_name='family',
            name='sponsors',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='intake.Sponsor', verbose_name='Sponsors'),
        ),
        migrations.AddField(
            model_name='family',
            name='travel_plans',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='intake.TravelPlan', verbose_name='Travel Plans'),
        ),
        migrations.AddField(
            model_name='intakebus',
            name='families',
            field=models.ManyToManyField(to='intake.Family', verbose_name='Families'),
        ),
        migrations.AlterField(
            model_name='family',
            name='days_detained',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Days spent in detention'),
        ),
        migrations.AlterField(
            model_name='family',
            name='days_traveling',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Days spent traveling'),
        ),
        migrations.AlterField(
            model_name='intakebus',
            name='arrival_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 6, 22, 9, 32, 984393, tzinfo=utc), verbose_name='Arrival time of bus'),
        ),
    ]
