# Generated by Django 2.2.1 on 2019-06-05 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0010_auto_20190604_0036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizations',
            name='head_email',
        ),
        migrations.RemoveField(
            model_name='organizations',
            name='head_name',
        ),
        migrations.RemoveField(
            model_name='organizations',
            name='head_phone_number',
        ),
        migrations.RemoveField(
            model_name='organizations',
            name='location',
        ),
        migrations.AddField(
            model_name='organizations',
            name='deputies',
            field=models.ManyToManyField(related_name='deputies', to='intake.Volunteers', verbose_name='Deputized volunteers'),
        ),
        migrations.AddField(
            model_name='organizations',
            name='location_city',
            field=models.CharField(max_length=500, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='organizations',
            name='location_state',
            field=models.CharField(choices=[('al', 'Alabama'), ('ak', 'Alaska'), ('az', 'Arizona'), ('ar', 'Arkansas'), ('ca', 'California'), ('co', 'Colorado'), ('ct', 'Connecticut'), ('de', 'Delaware'), ('dc', 'District of Columbia'), ('fl', 'Florida'), ('ga', 'Georgia'), ('hi', 'Hawaii'), ('id', 'Idaho'), ('il', 'Illinois'), ('in', 'Indiana'), ('ia', 'Iowa'), ('ks', 'Kansas'), ('ky', 'Kentucky'), ('la', 'Louisiana'), ('me', 'Maine'), ('md', 'Maryland'), ('ma', 'Massachusetts'), ('mi', 'Michigan'), ('mn', 'Minnesota'), ('ms', 'Mississippi'), ('mo', 'Missouri'), ('mt', 'Montana'), ('ne', 'Nebraska'), ('nv', 'Nevada'), ('nh', 'New Hampshire'), ('nj', 'New Jersey'), ('nm', 'New Mexico'), ('ny', 'New York'), ('nc', 'North Carolina'), ('nd', 'North Dakota'), ('oh', 'Ohio'), ('ok', 'Oklahoma'), ('or', 'Oregon'), ('pa', 'Pennsylvania'), ('pr', 'Puerto Rico'), ('ri', 'Rhode Island'), ('sc', 'South Carolina'), ('sd', 'South Dakota'), ('tn', 'Tennessee'), ('tx', 'Texas'), ('ut', 'Utah'), ('vt', 'Vermont'), ('va', 'Virginia'), ('wa', 'Washington State'), ('wv', 'West Virginia'), ('wi', 'Wisconsin'), ('wy', 'Wyoming'), ('other', 'Other')], max_length=1, null=True, verbose_name='State'),
        ),
        migrations.AddField(
            model_name='organizations',
            name='notes',
            field=models.TextField(null=True, verbose_name='Additional notes'),
        ),
        migrations.AddField(
            model_name='organizations',
            name='point_of_contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pointofcontact', to='intake.Volunteers', verbose_name='Point of contact'),
        ),
        migrations.AlterField(
            model_name='organizations',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='organizations',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Name of the organization'),
        ),
        migrations.AlterField(
            model_name='volunteertypes',
            name='volunteer_type',
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
