# Generated by Django 3.1.7 on 2021-03-31 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0010_auto_20210330_2009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donate',
            name='organization',
        ),
        migrations.AddField(
            model_name='donate',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Location'),
        ),
    ]
