# Generated by Django 3.1.6 on 2021-02-22 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0010_auto_20210221_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asylee',
            name='a_number',
            field=models.CharField(default='A-', max_length=20, verbose_name='Alien number'),
        ),
    ]
