# Generated by Django 2.2.1 on 2019-06-05 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0011_auto_20190605_0329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizations',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Additional notes'),
        ),
    ]
