# Generated by Django 3.1.6 on 2021-02-22 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0011_auto_20210221_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asylee',
            name='had_covid_disease',
            field=models.BooleanField(default=False, verbose_name='Has had COVID disease'),
        ),
        migrations.AlterField(
            model_name='asylee',
            name='had_covid_vaccine',
            field=models.BooleanField(default=False, verbose_name='Has receive the COVID vaccine'),
        ),
    ]
