# Generated by Django 3.1.6 on 2021-02-22 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0012_auto_20210221_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asylee',
            name='had_covid_vaccine',
            field=models.BooleanField(default=False, verbose_name='Has received the COVID vaccine'),
        ),
        migrations.AlterField(
            model_name='asylee',
            name='legal_done',
            field=models.BooleanField(default=True, verbose_name='Legal paperwork is done'),
        ),
        migrations.AlterField(
            model_name='asylee',
            name='sick_covid',
            field=models.BooleanField(default=False, verbose_name='Is currently sick from COVID'),
        ),
        migrations.AlterField(
            model_name='asylee',
            name='sick_other',
            field=models.BooleanField(default=False, verbose_name='Is currently sick but not from COVID'),
        ),
        migrations.AlterField(
            model_name='asylee',
            name='tsa_done',
            field=models.BooleanField(default=True, verbose_name='TSA paperwork is done'),
        ),
    ]
