# Generated by Django 3.1.7 on 2021-04-02 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0012_auto_20210401_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='asylee',
            name='needs_medical_attention',
            field=models.BooleanField(default=False, verbose_name='Needs medical attention'),
        ),
    ]
