# Generated by Django 2.2.3 on 2019-07-07 03:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0012_auto_20190706_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='intakebuses',
            field=models.ManyToManyField(to='intake.IntakeBus', verbose_name='Intake Buses'),
        ),
        migrations.AlterField(
            model_name='intakebus',
            name='arrival_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 7, 3, 8, 48, 943736, tzinfo=utc), verbose_name='Arrival time of bus'),
        ),
    ]
