# Generated by Django 3.1.6 on 2021-02-22 05:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0013_auto_20210221_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asylee',
            name='covid_vaccine_shots',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)], verbose_name='COVID vaccine shots received'),
        ),
        migrations.AlterField(
            model_name='asylee',
            name='vaccine_received',
            field=models.CharField(choices=[('pfizer', 'Pfizer'), ('moderna', 'Moderna'), ('j_and_j', 'Johnson & Johnson'), ('astra_zeneca', 'AstraZeneca'), ('other', 'Other')], max_length=100, null=True, verbose_name='Vaccine manufacturer'),
        ),
    ]
