# Generated by Django 2.2.3 on 2019-07-07 03:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0013_auto_20190706_2108'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asylee',
            old_name='medical',
            new_name='medicals',
        ),
        migrations.RenameField(
            model_name='family',
            old_name='sponsors',
            new_name='sponsor',
        ),
        migrations.RenameField(
            model_name='family',
            old_name='travel_plans',
            new_name='travel_plan',
        ),
        migrations.AlterField(
            model_name='intakebus',
            name='arrival_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 7, 3, 18, 10, 774928, tzinfo=utc), verbose_name='Arrival time of bus'),
        ),
    ]
