# Generated by Django 3.1.7 on 2021-04-02 02:09

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0013_asylee_needs_medical_attention'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='headofhousehold',
            name='languages',
        ),
        migrations.AddField(
            model_name='headofhousehold',
            name='languages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=['Spanish'], size=None, verbose_name='Languages Spoken'),
            preserve_default=False,
        ),
    ]
