# Generated by Django 3.1.6 on 2021-02-24 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0014_auto_20210221_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelplan',
            name='flight_number',
            field=models.CharField(max_length=200, null=True, verbose_name='Flight #(s)'),
        ),
        migrations.AddField(
            model_name='travelplan',
            name='layovers',
            field=models.CharField(max_length=300, null=True, verbose_name='Layover(s)'),
        ),
        migrations.AlterField(
            model_name='travelplan',
            name='eta',
            field=models.DateTimeField(null=True, verbose_name='Estimated arrival'),
        ),
        migrations.AlterField(
            model_name='travelplan',
            name='travel_mode',
            field=models.CharField(choices=[('Air', (('alaska', 'Alaska (AS)'), ('american', 'American (AA)'), ('delta', 'Delta (DL)'), ('frontier', 'Frontier (F9)'), ('jetblue', 'Jet Blue (B6)'), ('southwest', 'Southwest (WN)'), ('united', 'United (UA)'), ('airline_other', 'Other airline'))), ('Bus', (('greyhound', 'Greyhound'), ('bus_other', 'Other bus'))), ('Train', (('amtrak', 'Amtrak'),)), ('Car', (('personal_car', 'Personal car'),)), ('other', 'Other')], default='other', max_length=100, verbose_name='Mode of travel'),
        ),
    ]
