# Generated by Django 3.1.7 on 2021-04-02 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0014_auto_20210401_2009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='headofhousehold',
            name='languages',
        ),
        migrations.AddField(
            model_name='headofhousehold',
            name='languages',
            field=models.ManyToManyField(to='intake.Language', verbose_name='Languages Spoken'),
        ),
    ]
