# Generated by Django 2.2.1 on 2019-06-05 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0015_auto_20190605_0357'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capacities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Capacity')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Description of capacity')),
            ],
        ),
    ]
