# Generated by Django 3.1.7 on 2021-04-02 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0015_auto_20210401_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='headofhousehold',
            name='detention_type',
            field=models.CharField(choices=[('mpp', 'Migrant Protection Protocols (MPP)'), ('cbp', 'Customs and Border Protection (CBP)'), ('other', 'Other')], default='other', max_length=100),
        ),
    ]
