# Generated by Django 2.2.1 on 2019-06-05 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0016_capacities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capacities',
            name='name',
            field=models.CharField(max_length=500, unique=True, verbose_name='Capacity'),
        ),
    ]
