# Generated by Django 3.1.7 on 2021-04-02 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0017_householdneed'),
    ]

    operations = [
        migrations.AddField(
            model_name='headofhousehold',
            name='departure_bag_made',
            field=models.BooleanField(default=False, verbose_name='Departure bags made'),
        ),
    ]
