# Generated by Django 2.2.1 on 2019-06-05 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0017_auto_20190605_0407'),
    ]

    operations = [
        migrations.CreateModel(
            name='LodgingTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lodging_type', models.CharField(max_length=50, unique=True, verbose_name='State')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Description of capacity')),
            ],
        ),
    ]
