# Generated by Django 3.1.7 on 2021-04-02 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0018_headofhousehold_departure_bag_made'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='associated_airport',
            field=models.CharField(choices=[('abq', 'Albuquerque International Sunport (ABQ)'), ('elp', 'El Paso International Airport')], default='abq', max_length=150),
        ),
    ]
