# Generated by Django 2.2.1 on 2019-06-05 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0018_lodgingtypes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=500, unique=True, verbose_name='Language')),
            ],
        ),
        migrations.RemoveField(
            model_name='volunteers',
            name='volunteer_type',
        ),
        migrations.AddField(
            model_name='volunteers',
            name='capacities',
            field=models.ManyToManyField(to='intake.Capacities', verbose_name='Volunteer capacities'),
        ),
        migrations.AlterField(
            model_name='volunteers',
            name='email',
            field=models.EmailField(max_length=300, null=True, verbose_name="Volunteer's email"),
        ),
        migrations.AlterField(
            model_name='volunteers',
            name='name',
            field=models.CharField(max_length=300, verbose_name="Volunteer's name"),
        ),
        migrations.AlterField(
            model_name='volunteers',
            name='organizations',
            field=models.ManyToManyField(to='intake.Organizations', verbose_name='Organizations to which the volunteer belongs'),
        ),
        migrations.AlterField(
            model_name='volunteers',
            name='phone_number',
            field=models.CharField(max_length=300, verbose_name="Volunteer's phone number"),
        ),
    ]
