# Generated by Django 2.2.1 on 2019-06-05 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0019_auto_20190605_0427'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteers',
            name='languages',
            field=models.ManyToManyField(to='intake.Languages', verbose_name='Languages spoken'),
        ),
    ]
