# Generated by Django 3.1.7 on 2021-04-02 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0019_organization_associated_airport'),
    ]

    operations = [
        migrations.AddField(
            model_name='headofhousehold',
            name='needs',
            field=models.ManyToManyField(default=None, to='intake.HouseholdNeed', verbose_name='Household Needs'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='specialty',
            field=models.CharField(choices=[('clothes', 'Clothes'), ('departurebags', 'Departure Bags'), ('food', 'Food'), ('hotelrunner', 'Hotel Runner'), ('intake', 'Intake'), ('travel', 'Travel'), ('transportation', 'Transportation'), ('volunteercoordinator', 'Volunteer Coordinator'), ('other', 'Other')], default='other', max_length=100, verbose_name='Team lead area'),
        ),
    ]
