# Generated by Django 2.2.1 on 2019-06-05 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0020_volunteers_languages'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizations',
            name='url',
            field=models.CharField(max_length=500, null=True, verbose_name='Website'),
        ),
    ]
