# Generated by Django 2.2.1 on 2019-06-05 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0021_organizations_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organizations',
            old_name='location_city',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='organizations',
            old_name='location_state',
            new_name='state',
        ),
    ]
