# Generated by Django 3.1.7 on 2021-04-05 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0022_historicalasylee_historicalheadofhousehold_historicalintakebus_historicallocation_historicalorganiza'),
    ]

    operations = [
        migrations.AddField(
            model_name='headofhousehold',
            name='food_made',
            field=models.BooleanField(default=False, verbose_name='Travel food made'),
        ),
        migrations.AddField(
            model_name='historicalheadofhousehold',
            name='food_made',
            field=models.BooleanField(default=False, verbose_name='Travel food made'),
        ),
    ]
