# Generated by Django 2.2.1 on 2019-06-06 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0022_auto_20190605_0508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteers',
            name='organizations',
        ),
        migrations.AddField(
            model_name='volunteers',
            name='affiliations',
            field=models.ManyToManyField(to='intake.Organizations', verbose_name='Organizations to which the volunteer is affiliated'),
        ),
    ]
