# Generated by Django 2.2.1 on 2019-06-11 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0024_auto_20190606_0157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizations',
            name='name',
            field=models.CharField(max_length=500, unique=True, verbose_name='Name of the organization'),
        ),
    ]
