# Generated by Django 2.2.1 on 2019-06-12 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0026_auto_20190611_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='locations',
            name='organization',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='intake.Organizations'),
        ),
        migrations.AlterField(
            model_name='locations',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
