# Generated by Django 2.2.1 on 2019-06-13 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0003_auto_20190528_1558'),
        ('intake', '0027_auto_20190612_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteers',
            name='campaigns',
            field=models.ManyToManyField(to='shortener.UrlMap', verbose_name='Active intake campaigns'),
        ),
    ]
