CAPACITY_CHOICES = [
    ('clothes', 'Clothes'),
    ('concierge', 'Concierge'),
    ('departurebags', 'Departure Bags'),
    ('food', 'Food'),
    ('intake', 'Intake'),
    ('travel', 'Travel'),
    ('transportation', 'Transportation'),
    ('volunteercoordinator', 'Volunteer Coordinator'),
    ('other', 'Other'),
]
COUNTRY_CHOICES = [
    ('The Americas', (
        ("guatemala", "Guatemala"),
        ("honduras", "Honduras"),
        ("elsalvador", "El Salvador"),
        ("mexico", "Mexico"),
        ("argentina", "Argentina"),
        ("bolivia", "Bolivia"),
        ("brazil", "Brazil"),
        ("chile", "Chile"),
        ("colombia", "Colombia"),
        ("costarica", "Costa Rica"),
        ("cuba", "Cuba"),
        ("dominicanrepublic", "Dominican Republic"),
        ("ecuador", "Ecuador"),
        ("frenchguiana", "French Guiana"),
        ("guadeloupe", "Guadeloupe"),
        ("haiti", "Haiti"),
        ("martinique", "Martinique"),
        ("mexico", "Mexico"),
        ("nicaragua", "Nicaragua"),
        ("panama", "Panama"),
        ("paraguay", "Paraguay"),
        ("peru", "Peru"),
        ("saintmartin", "Saint Martin"),
        ("uruguay", "Uruguay"),
        ("venezuela", "Venezuela"),
        )
    ),
    ('Africa', (
        ("algeria","Algeria"),
        ("angola","Angola"),
        ("benin","Benin"),
        ("botswana","Botswana"),
        ("burkinafaso","Burkina Faso"),
        ("burundi","Burundi"),
        ("cameroon","Cameroon"),
        ("canaryislands","Canary Islands"),
        ("capeverde","Cape Verde"),
        ("centralafricanrepublic","Central African Republic"),
        ("ceuta","Ceuta"),
        ("chad","Chad"),
        ("comoros","Comoros"),
        ("cotedivoire","Côte d'Ivoire"),
        ("democraticrepublicofthecongo","Democratic Republic of the Congo"),
        ("djibouti","Djibouti"),
        ("egypt","Egypt"),
        ("equatorialguinea","Equatorial Guinea"),
        ("eritrea","Eritrea"),
        ("ethiopia","Ethiopia"),
        ("gabon","Gabon"),
        ("gambia","Gambia"),
        ("ghana","Ghana"),
        ("guinea","Guinea"),
        ("guinea-bissau","Guinea-Bissau"),
        ("kenya","Kenya"),
        ("lesotho","Lesotho"),
        ("liberia","Liberia"),
        ("libya","Libya"),
        ("madagascar","Madagascar"),
        ("madeira","Madeira"),
        ("malawi","Malawi"),
        ("mali","Mali"),
        ("mauritania","Mauritania"),
        ("mauritius","Mauritius"),
        ("mayotte","Mayotte"),
        ("melilla","Melilla"),
        ("morocco","Morocco"),
        ("mozambique","Mozambique"),
        ("namibia","Namibia"),
        ("niger","Niger"),
        ("nigeria","Nigeria"),
        ("republicofthecongo","Republic of the Congo"),
        ("reunion","Réunion"),
        ("rwanda","Rwanda"),
        ("sainthelena","Saint Helena"),
        ("saotomeandpríncipe","São Tomé and Príncipe"),
        ("senegal","Senegal"),
        ("seychelles","Seychelles"),
        ("sierraleone","Sierra Leone"),
        ("somalia","Somalia"),
        ("southafrica","South Africa"),
        ("sudan","Sudan"),
        ("swaziland","Swaziland"),
        ("tanzania","Tanzania"),
        ("togo","Togo"),
        ("tunisia","Tunisia"),
        ("uganda","Uganda"),
        ("westernsahara","Western Sahara"),
        ("zambia","Zambia"),
        ("zimbabwe","Zimbabwe"),
        )
    ),
    ('other','Other'),
]
LANGUAGE_CHOICES = [
    ('Latin', (
            ('english', 'English'),
            ('spanish', 'Spanish'),
            ('portuguese', 'Portuguese'),
            ('french', 'French'),
        )
    ),
    ('Maya', (
            ("achi", "Achi"),
            ("awakatek", "Awakatek"),
            ("chorti", "Ch\'orti\'"),
            ("chuj", "Chuj"),
            ("itza", "Itza\'"),
            ("ixil", "Ixil"),
            ("jakaltek", "Jakaltek"),
            ("kiche", "K\'iche\'"),
            ("kaqchiquel", "Kaqchiquel"),
            ("mam", "Mam"),
            ("mopan", "Mopan"),
            ("poqomam", "Poqomam"),
            ("poqomchi", "Poqomchi\'"),
            ("qanjobal", "Q\'anjob\'al"),
            ("qeqchi", "Q\'eqchi\'"),
            ("sakapultek", "Sakapultek"),
            ("sipakapense", "Sipakapense"),
            ("tektitek", "Tektitek"),
            ("tzutujil", "Tz\'utujil"),
            ("upsantek", "Upsantek"),
        )
    ),
    ('other','Other')
]
LODGING_CHOICES = [
    ('dormitory','Dormitory'),
    ('hotel','Hotel'),
    ('motel','Motel'),
    ('other','Other'),
]
STATE_CHOICES = [
    ('al', 'Alabama'),
    ('ak', 'Alaska'),
    ('az', 'Arizona'),
    ('ar', 'Arkansas'),
    ('ca', 'California'),
    ('co', 'Colorado'),
    ('ct', 'Connecticut'),
    ('de', 'Delaware'),
    ('dc', 'Washington D.C.'),
    ('fl', 'Florida'),
    ('ga', 'Georgia'),
    ('hi', 'Hawaii'),
    ('id', 'Idaho'),
    ('il', 'Illinois'),
    ('in', 'Indiana'),
    ('ia', 'Iowa'),
    ('ks', 'Kansas'),
    ('ky', 'Kentucky'),
    ('la', 'Louisiana'),
    ('me', 'Maine'),
    ('md', 'Maryland'),
    ('ma', 'Massachusetts'),
    ('mi', 'Michigan'),
    ('mn', 'Minnesota'),
    ('ms', 'Mississippi'),
    ('mo', 'Missouri'),
    ('mt', 'Montana'),
    ('ne', 'Nebraska'),
    ('nv', 'Nevada'),
    ('nh', 'New Hampshire'),
    ('nj', 'New Jersey'),
    ('nm', 'New Mexico'),
    ('ny', 'New York'),
    ('nc', 'North Carolina'),
    ('nd', 'North Dakota'),
    ('oh', 'Ohio'),
    ('ok', 'Oklahoma'),
    ('or', 'Oregon'),
    ('pa', 'Pennsylvania'),
    ('pr', 'Puerto Rico'),
    ('ri', 'Rhode Island'),
    ('sc', 'South Carolina'),
    ('sd', 'South Dakota'),
    ('tn', 'Tennessee'),
    ('tx', 'Texas'),
    ('ut', 'Utah'),
    ('vt', 'Vermont'),
    ('va', 'Virginia'),
    ('wa', 'Washington State'),
    ('wv', 'West Virginia'),
    ('wi', 'Wisconsin'),
    ('wy', 'Wyoming'),
    ('other', 'Other')
]
SEX_CHOICES = [
    ('female', 'Female'),
    ('male', 'Male'),
    ('other', 'Other'),
]
TRAVEL_MODE_CHOICES = [
    ('Air', (
            ('alaska', 'Alaska (AS)'),
            ('american', 'American (AA)'),
            ('delta', 'Delta (DL)'),
            ('frontier', 'Frontier (F9)'),
            ('jetblue', 'Jet Blue (B6)'),
            ('southwest', 'Southwest (WN)'),
            ('united', 'United (UA)'),
            ('airline_other', 'Other airline'),
        )
    ),
    ('Bus', (
            ('greyhound', 'Greyhound'),
            ('bus_other', 'Other bus'),
        )
    ),
    ('Train', (
            ('amtrak', 'Amtrak'),
        )
    ),
    ('Car', (
            ('personal_car', 'Personal car'),
        )
    ),
    ('other', 'Other'),
]
COVID_VACCINE_CHOICES = [
    ('pfizer', 'Pfizer'),
    ('moderna', 'Moderna'),
    ('j_and_j', 'Johnson & Johnson'),
    ('astra_zeneca', 'AstraZeneca'),
    ('unknown', 'Unknown'),
    ('other', 'Other'),
]
ROLE_CHOICES = [
    ('volunteer', 'Volunteer'),
    ('team_lead','Team Lead'),
    ('site_coordinator','Site Coordinator'),
]
DETENTION_TYPE_CHOICES = [
    ('mpp', 'Migrant Protection Protocols (MPP)'),
    ('cbp', 'Customs and Border Protection (CBP)'),
    ('other', 'Other'),
]
AIRPORT_CHOICES = [
    ('abq', 'Albuquerque International Sunport (ABQ)'),
    ('elp', 'El Paso International Airport'),
]